### ISSUE TITLE
admin/admin 登陆后页面不跳转

### ISSUE THREAD

**Issue by haoglehaogle** [chenhg5/go-admin#12]
go run example/gin/main.go 后登陆一直停留在登陆页面。

**Comment by chenhg5** [comment]
@haoglehaogle 检查一下域名，配置项中有一项是domain，要一致才行

**Comment by haoglehaogle** [comment]
@chenhg5 config.go文件里面？ 提供一下config example？

**Comment by chenhg5** [comment]
@haoglehaogle https://github.com/chenhg5/go-admin/blob/master/examples/gin/main.go#L32
