### ISSUE TITLE
多个AreaChart生成js代码报错

### ISSUE THREAD

**Issue by chengruiluck** [chenhg5/go-admin#16]
当添加多个AreaChart的时候，生成的js代码会多次生成
let salesChartCanvas = $('#{{.ID}}').get(0).getContext('2d');

页面会报错
uncaught SyntaxError: Identifier 'salesChartCanvas' has already been declared

**Comment by chenhg5** [comment]
@chengruiluck 感谢反馈，我跟进下

**Comment by chenhg5** [comment]
@chengruiluck 已修复。更新一下代码。go get -u -v github.com/chenhg5/go-admin
