### ISSUE TITLE
为什么不做成前后端分离的

### ISSUE THREAD

**Issue by 107295472** [chenhg5/go-admin#2]
模版的性能和体验都不好

**Comment by chenhg5** [comment]
考虑后面版本做，因为是参考了别的项目是模板化的，这样的话使用模板开发，可以很快出功能完整的第一版，而选择前后端分离工作量会加大。在之后的版本可以迭代成前后端分离的。同时后面也会计划使用[electron](https://github.com/electron/electron)做桌面版本的支持。
