### ISSUE TITLE
一直302跳转回login界面

### ISSUE THREAD

**Issue by zsqutoutiao** [chenhg5/go-admin#24]

**Comment by zsqutoutiao** [comment]
找到原因了，origin设置的问题，导致浏览器没有正确设置cookie

**Comment by nimohunter** [comment]
由于跨域导致没有正确设置cookie， 正确的本地启动的做法是将  demo/main.go 的 32行DOMAIN 设置为 localhost。 然后再使用localhost:9033/admin/login 进行登录。
