### ISSUE TITLE
interface conversion: interface {} is []uint8, not string

### ISSUE THREAD

**Issue by majunli1986** [chenhg5/go-admin#27]
interface conversion: interface {} is []uint8, not string
window操作系统，mysql数据库，总是报错。这个和go版本有关么？
go version go1.12.4 windows/amd64

**Comment by chenhg5** [comment]
@majunli1986 你使用了 go mod 的吗，[mysql驱动](github.com/go-sql-driver/mysql)版本是多少

**Comment by majunli1986** [comment]
> @majunli1986 你使用了 go mod 的吗，[mysql驱动](github.com/go-sql-driver/mysql)版本是多少

加个微信？bnueplee

**Comment by majunli1986** [comment]
mysql版本 5.6.16-log

**Comment by majunli1986** [comment]
![image](https://user-images.githubusercontent.com/48741334/56800589-fc873280-684d-11e9-9896-45a8ea6b221a.png)
这里 select出来的，都是[]uint8类型的interface。

**Comment by majunli1986** [comment]
> go mod

对了，我不是用go mod管理的

**Comment by majunli1986** [comment]
B2S(menus[i]["title"].([]uint8))

func B2S(bs []uint8) string {
	ba := []byte{}
	for _, b := range bs {
		ba = append(ba, byte(b))
	}
	return string(ba)
}
这是我修改的，希望赶紧回复并修复

**Comment by kitech** [comment]
看上去是mysql driver版本的问题，我更新了一下好了，

`go get -v -u github.com/go-sql-driver/mysql`
