### ISSUE TITLE
mysql blob类型不显示

### ISSUE THREAD

**Issue by dreamlu** [chenhg5/go-admin#30]

**Comment by dreamlu** [comment]
第一次用，不太明白如何做，打扰了

**Comment by dreamlu** [comment]
还有docker化时，这里的静态资源引入会有问题，部署成https 控制台会报错(改成了http才行)

**Comment by chenhg5** [comment]
> 第一次用，不太明白如何做，打扰了；另外，为何接口的调用形式前后端不分离呢；

工作量大，且不能合并成一个二进制文件。前后端分离主要是性能跟体验提升，本项目性能没有需求，体验上用了pjax技术也不比前后端分离差。因此没有考虑分离。

> 另外，如何进行字段修改新增过滤后插入数据库(如密码的修改,需要加密后存储，而不是直接修改了)

暂不支持的，后面会支持。

> 还有docker化时，这里的静态资源引入会有问题，部署成https 控制台会报错(改成了http才行)

暂不支持https，后续改进。

@dreamlu blob类型的场景是什么？你们用blob类型需要怎么显示？之前确实没有考虑到这个。

**Comment by dreamlu** [comment]
blob存储一些表情符号等昵称

**Comment by chenhg5** [comment]
- [x] 新增过滤后插入数据库

新增postfun类型支持，详见[这里](https://github.com/chenhg5/go-admin/blob/065017835d3a2a3e5348480af90e8958ec3b5280/template/types/types.go#L75)

**Comment by dreamlu** [comment]
close
