### ISSUE TITLE
mac使用sqlite报错

### ISSUE THREAD

**Issue by uucp** [chenhg5/go-admin#44]
可登录，进入用户、角色、权限、菜单、操作日志都报错
{"code":500,"msg":"interface conversion: interface {} is string, not []uint8"}

plugins⁩/admin/⁨models⁩/table.go  461
		columns[key] = string(model["name"].([]uint8))
改为			columns[key] = string(model["name"].(string))
可浏览了

**Comment by chenhg5** [comment]
@uucp 本地 sqlite 驱动版本是多少

**Comment by chenhg5** [comment]
@uucp 看是否一致 https://github.com/chenhg5/go-admin/blob/master/go.mod#L26

**Comment by uucp** [comment]
github.com/chenhg5/go-admin@v0.0.4 github.com/mattn/go-sqlite3@v1.10.0

**Comment by chenhg5** [comment]
已修复，见：[#16f1195](https://github.com/chenhg5/go-admin/commit/16f11951be4faba2b4366496836d6d9d5c9ec4c1)
