### ISSUE TITLE
新创建管理员的管理员不能登录

### ISSUE THREAD

**Issue by uucp** [chenhg5/go-admin#46]
password 没有 EncodePassword
manager.go 
import  "github.com/chenhg5/go-admin/modules/auth"

 21   "password": dataList["password"][0],
改为 "password": auth.EncodePassword([]byte(dataList["password"][0])),

问题解决

**Comment by chenhg5** [comment]
@uucp 发布了新的版本0.0.7，用最新版本吧。旧版本可能有一些问题。
