### ISSUE TITLE
Feat : adapter for Buffalo Go framework

### ISSUE THREAD

**Issue by hubyhuby** [chenhg5/go-admin#49]
Buffalo is a popular framework for GO with over 4 700 stars and 120+ contributors.
It would be super cool, if you would suport it aswell.
https://github.com/gobuffalo/buffalo

Let me know if you have an adapter to test for Buffalo.

Thanks for this amazing work, looking forward to test it ;)

**Comment by chenhg5** [comment]
@hubyhuby working on it

**Comment by hubyhuby** [comment]
Great , looking forward to test it.
Note that there is a buffalo slack here, with very helpful persons :
https://app.slack.com/client/T029RQSE6/C3MSAFD40/thread/C3MSAFD40-1565569187.323500

**Comment by hubyhuby** [comment]
Dear Chen,
I have tried the example you provided for buffalo, but couldn t get it to work.
I get an error with modules when building : 
"
build thingys/go-admin: cannot load github.com/chenhg5/go-admin/adapter/buffalo: cannot find module providing package github.com/chenhg5/go-admin/adapter/buffalo
"

--------
With GO111MODULE=on
I have the following go.mod generated by go :
"
module thingys/go-admin

go 1.12

require (
	github.com/chenhg5/go-admin v0.0.4
	github.com/chenhg5/go-admin/modules/db v0.0.0-20190816024035-6a35a24e146b // indirect
	github.com/cockroachdb/cockroach-go v0.0.0-20181001143604-e0a95dfd547c // indirect
	github.com/gobuffalo/buffalo v0.14.9
	github.com/kr/pty v1.1.3 // indirect
)

"
**When I build I get :**  
/thingys/go-admin$ go build
go: finding github.com/chenhg5/go-admin/adapter/buffalo latest
go: finding github.com/chenhg5/go-admin/adapter latest
build thingys/go-admin: cannot load github.com/chenhg5/go-admin/adapter/buffalo: cannot find module providing package github.com/chenhg5/go-admin/adapter/buffalo

**Comment by chenhg5** [comment]
@hubyhuby You should use the latest version. v0.0.4 is old version which doesn't support the buffalo adapter.

**Comment by hubyhuby** [comment]
Whaou @chenhg5 ,
Thanks for your super fast answer !
Now I managed to compile ;) Trying to get the connexion to postgres but crashing  because of "goadmin_roles".
Is there a doc explaining what I shall set extra in my postgres table ?
[go-admin-buffalo-compiling-oura.zip](https://github.com/chenhg5/go-admin/files/3538202/go-admin-buffalo-compiling-oura.zip)
----------------------

"
/thingys/go-admin$ ./go-admin
WARN[0000] go-admin is now running.
Running in "debug" mode. Switch to "release" mode in production.
 
panic: pq: relation "goadmin_roles" does not exist

goroutine 1 [running]:
github.com/chenhg5/go-admin/modules/db/performer.Query(0xc000108180, 0xc000401bc0, 0x2f, 0xc0003ccd00, 0x1, 0x1, 0xffffffffffffffff, 0xc000401bc0, 0x2f, 0x0)
	/home/MEE/Dropbox/go/pkg/mod/github.com/chenhg5/go-admin/modules/db@v0.0.0-20190816024035-6a35a24e146b/performer/performer.go:22 +0x785
github.com/chenhg5/go-admin/modules/db/postgresql.(*Postgresql).Query(0x1f8c2e0, 0xc000401bc0, 0x2f, 0xc0003ccd00, 0x1, 0x1, 0x20, 0x1, 0xc0003ccd00, 0xc0004bea20)
	/home/MEE/Dropbox/go/pkg/mod/github.com/chenhg5/go-admin/modules/db@v0.0.0-20190816024035-6a35a24e146b/postgresql/postgresql.go:40 +0x27a
github.com/chenhg5/go-admin/modules/db.(*Sql).All(0xc00014cb00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/MEE/Dropbox/go/pkg/mod/github.com/chenhg5/go-admin/modules/db@v0.0.0-20190816024035-6a35a24e146b/statement.go:207 +0xd6
github.com/chenhg5/go-admin/plugins/admin/models.GetMenuTable(0xc000313730, 0xc0004c22a0)
	/home/MEE/Dropbox/go/pkg/mod/github.com/chenhg5/go-admin@v0.0.5-0.20190816024035-6a35a24e146b/plugins/admin/models/generators.go:773 +0x7fe
github.com/chenhg5/go-admin/plugins/admin/models.InitTableList()
	/home/MEE/Dropbox/go/pkg/mod/github.com/chenhg5/go-admin@v0.0.5-0.20190816024035-6a35a24e146b/plugins/admin/models/table.go:23 +0xfa
github.com/chenhg5/go-admin/plugins/admin.(*Admin).InitPlugin(0xc0004181a0)
	/home/MEE/Dropbox/go/pkg/mod/github.com/chenhg5/go-admin@v0.0.5-0.20190816024035-6a35a24e146b/plugins/admin/admin.go:39 +0x499
github.com/chenhg5/go-admin/engine.(*Engine).AddPlugins(0xc000313e60, 0xc000313e40, 0x2, 0x2, 0x9)
	/home/MEE/Dropbox/go/pkg/mod/github.com/chenhg5/go-admin@v0.0.5-0.20190816024035-6a35a24e146b/engine/engine.go:43 +0x65
main.main()
	/home/MEE/Dropbox/go/src/thingys/go-admin/main.go:58 +0x225

---------------------------------------------


For reference go getting like this make it pass the compilation, with the latest go-admin master :
go get github.com/chenhg5/go-admin@master

Note that by default go mod init generates a go.mod with  0.0.4

**Comment by chenhg5** [comment]
@hubyhuby Have you imported [the specified sql file](https://github.com/chenhg5/go-admin/blob/master/examples/datamodel/admin.pgsql) into the database? Yes, there is a doc here https://github.com/chenhg5/go-admin/blob/master/docs/en/instruction/instruction.md.
