### ISSUE TITLE
[Proposal] rename ExcuFun to FilterFn to make it easier to understand

### ISSUE THREAD

**Issue by eugeneradionov** [chenhg5/go-admin#54]
## Idea
Let's rename `ExcuFun` to `FilterFunc` or `FilterFn` because it is too hard to guess what is this function and what does it must do.
The same logic can be applicable for `FieldValueFun` => `FieldFilterFn`

```go
type FieldValueFun func(value RowModel) interface{}

type Field struct {
	ExcuFun   FieldValueFun
	Field     string
	TypeName  string
	Head      string
	JoinTable []Join
	Sortable  bool
	Filter    bool
	Hide      bool
}
```

**Comment by chenhg5** [comment]
@eugeneradionov I agree with that. `FilterFn ` and  `FieldFilterFn ` are ok.
