### ISSUE TITLE
下拉框的选项，为另一个表的记录

### ISSUE THREAD

**Issue by hou-rong** [chenhg5/go-admin#56]
以当前 User 和 City 的关系为例
![image](https://user-images.githubusercontent.com/8758438/63454326-30313c80-c47d-11e9-862a-4ad125cf57c3.png)

希望 User 的 City 选项，为另一个表 City 的记录

**Comment by chenhg5** [comment]
@hou-rong 可以参考这里 https://github.com/chenhg5/go-admin/blob/master/plugins/admin/models/generators.go#L159

**Comment by hou-rong** [comment]
好的，十分感谢🙏
