### ISSUE TITLE
[31mgo-admin cli error: no tables[0m

### ISSUE THREAD

**Issue by hijaumuda** [chenhg5/go-admin#59]
im run admincli generate, and got error no tables.

C:\Users\Dimas\go\src>admincli generate
[H[2JGoAdmin CLI v1.0.0
? choose a driver mysql
? sql address 127.0.0.1
? sql port 3306
? sql username root
? sql password
? sql database name godmin

[31mgo-admin cli error: no tables[0m

**Comment by chenhg5** [comment]
@hijaumuda your should create sql tables of your own service first.

**Comment by hijaumuda** [comment]
> @hijaumuda your should create sql tables of your own service first.

thank you 👌
