### ISSUE TITLE
一个小错误

### ISSUE THREAD

**Issue by ha666** [chenhg5/go-admin#61]
http://doc.go-admin.cn/#/
打开这个网站，搜索“开箱即用的”，可以看到一个错误，应该是“开箱即用的rbac认证系统”
![QQ截图20190910213123](https://user-images.githubusercontent.com/4374328/64618194-60338600-d412-11e9-81f3-8355505b1880.png)

**Comment by chenhg5** [comment]
@ha666 感谢反馈，已更正
